# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1c\n\tUserReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x19\n\x08UserList\x12\r\n\x05users\x18\x01 \x03(\t2d\n\x0bUserService\x12+\n\x05Login\x12\x11.chat.UserRequest\x1a\x0f.chat.UserReply\x12(\n\tListUsers\x12\x0b.chat.Empty\x1a\x0e.chat.UserListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=20
  _globals['_USERREQUEST']._serialized_end=51
  _globals['_USERREPLY']._serialized_start=53
  _globals['_USERREPLY']._serialized_end=81
  _globals['_EMPTY']._serialized_start=83
  _globals['_EMPTY']._serialized_end=90
  _globals['_USERLIST']._serialized_start=92
  _globals['_USERLIST']._serialized_end=117
  _globals['_USERSERVICE']._serialized_start=119
  _globals['_USERSERVICE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
